### ISSUE TITLE
What does Pacman stand for?

### ISSUE THREAD

**Issue by baltaazr** [ian13456/pacman#1]
There's messages in every game. Like Pac-Man.
Do you know what PAC stands for? "Program and Control." He's Program and Control Man,
the whole thing's a metaphor, he thinks he's got free will
but really he's trapped in a maze, in a system, all he can do is consume, he's pursued by demons
that are probably just in his own head, and even if he does manage to escape
by slipping out one side of the maze, what happens?
He comes right back in the other side. People think it's a happy game, it's not a happy game,
it's a f****** nightmare world and the worst thing is
it's real and we live in it.

**Comment by shaoruu** [comment]
there was like a
